# Generated by Django 3.1.7 on 2021-04-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Parkir',
        ),
    ]
