# Generated by Django 3.1.7 on 2021-04-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkir', '0002_auto_20210403_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkir',
            old_name='title',
            new_name='Title',
        ),
    ]
